apiVersion: v1 
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - name: memory-demo-ctr
      image: polinux/stress
      resources:
        limits:
          memory: "1Gi"
        requests:
          memory: "1Gi"
      command: ["stress"]
      args: ["--vm","1","--vm-bytes","150Mi","--vm-/hang","1"]
# this code will make error because u exceed limit of memory-demo