apiVersion: v1 
kind: Pod 
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis 
  initContainers:
   - name: busy
     image: busybox
     command: ['sh','-c','sleep 20']
     