apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
spec:
 containers:
  - name: nginx
    image: nginx:latest
    envFrom:
      - configMapRef:
          name: webapp-config-map
    # env: 
    #   - name:  APP_COLOR #this name in application
    #     valueFrom:
    #       configRefKey:
    #         name: webapp-config-map
    #         key: APP_COLOR #this name in configfile 